export const ElectronMetadataNames = {
  IpcChannelParameters: 'ipc.channel.parameters',
  IpcResultParameters: 'ipc.result.parameters',
  WindowDefinition: 'window.definition',
  MenuDefinition: 'menu.definition',
  WindowUseMenuDefinition: 'window.use-menu.definition',
  WindowRendererDefinition: 'window.renderer.definition',
  MenuRendererDefinition: 'menu.renderer.definition',
  WindowCommand: 'window.command',
  MenuCommand: 'menu.command',
  WindowEmit: 'window.emit',
  MenuItem: 'menu.item',
  WindowRendererSubscription: 'window.renderer.subscription',
  MenuRendererSubscription: 'menu.renderer.subscription',
  WindowMainSubscription: 'window.main.subscription',
} as const;
