import { electronMetadata } from './electron-metadata.shared';
import { ElectronMetadataNames } from './electron-metadata.names';

export * from './electron-metadata.types';
export * from './electron-metadata.names';
export type {
  ElectronWindowDefinitionMetadata,
  ElectronMenuDefinitionMetadata,
  WindowUseMenuDefinitionMetadata,
  MenuContributionDefinitionMetadata,
  MenuFragmentDefinitionMetadata,
  MenuItemLabelResolverContext,
  MenuItemLabelValue,
  MenuItemMetadataEntry,
  RendererIpcSubscriptionType,
  WindowRendererSubscriptionMetadata,
  MenuRendererSubscriptionMetadata,
  WindowMainSubscriptionMetadata,
} from './electron-metadata.types';

export {
  setIpcChannelParameterIndices,
  getIpcChannelParameterIndices,
  setIpcResultParameterIndices,
  getIpcResultParameterIndices,
} from './electron-metadata.ipc';

export {
  setWindowDefinitionMetadata,
  getWindowDefinitionMetadata,
  setMenuDefinitionMetadata,
  getMenuDefinitionMetadata,
  setWindowUseMenuDefinitionMetadata,
  getWindowUseMenuDefinitionMetadata,
  setMenuContributionDefinitionMetadata,
  getMenuContributionDefinitionMetadata,
  setMenuFragmentDefinitionMetadata,
  getMenuFragmentDefinitionMetadata,
  setWindowRendererDefinitionMetadata,
  getWindowRendererDefinitionMetadata,
  setMenuRendererDefinitionMetadata,
  getMenuRendererDefinitionMetadata,
} from './electron-metadata.class-definitions';

export {
  addWindowCommandMetadata,
  getWindowCommandMetadata,
  addMenuCommandMetadata,
  getMenuCommandMetadata,
  addMenuItemMetadata,
  getMenuItemMetadata,
  addMenuItemHandleInMainMetadata,
  getMenuItemHandleInMainMetadata,
  addMenuItemForwardToRendererMetadata,
  getMenuItemForwardToRendererMetadata,
  addWindowEmitMetadata,
  getWindowEmitMetadata,
  getWindowEmitMetadataForMethod,
  addWindowRendererSubscriptionMetadata,
  getWindowRendererSubscriptionMetadata,
  addMenuRendererSubscriptionMetadata,
  getMenuRendererSubscriptionMetadata,
  addWindowMainSubscriptionMetadata,
  getWindowMainSubscriptionMetadata,
} from './electron-metadata.methods';

import {
  setIpcChannelParameterIndices,
  getIpcChannelParameterIndices,
  setIpcResultParameterIndices,
  getIpcResultParameterIndices,
} from './electron-metadata.ipc';

import {
  setWindowDefinitionMetadata,
  getWindowDefinitionMetadata,
  setMenuDefinitionMetadata,
  getMenuDefinitionMetadata,
  setWindowUseMenuDefinitionMetadata,
  getWindowUseMenuDefinitionMetadata,
  setMenuContributionDefinitionMetadata,
  getMenuContributionDefinitionMetadata,
  setMenuFragmentDefinitionMetadata,
  getMenuFragmentDefinitionMetadata,
  setWindowRendererDefinitionMetadata,
  getWindowRendererDefinitionMetadata,
  setMenuRendererDefinitionMetadata,
  getMenuRendererDefinitionMetadata,
} from './electron-metadata.class-definitions';

import {
  addWindowCommandMetadata,
  getWindowCommandMetadata,
  addMenuCommandMetadata,
  getMenuCommandMetadata,
  addMenuItemMetadata,
  getMenuItemMetadata,
  addMenuItemHandleInMainMetadata,
  getMenuItemHandleInMainMetadata,
  addMenuItemForwardToRendererMetadata,
  getMenuItemForwardToRendererMetadata,
  addWindowEmitMetadata,
  getWindowEmitMetadata,
  getWindowEmitMetadataForMethod,
  addWindowRendererSubscriptionMetadata,
  getWindowRendererSubscriptionMetadata,
  addMenuRendererSubscriptionMetadata,
  getMenuRendererSubscriptionMetadata,
  addWindowMainSubscriptionMetadata,
  getWindowMainSubscriptionMetadata,
} from './electron-metadata.methods';

export const ElectronMetadataStorage = {
  names: ElectronMetadataNames,
  getKey(name: keyof typeof ElectronMetadataNames): string {
    return electronMetadata.getKey(ElectronMetadataNames[name]);
  },
  setIpcChannelParameterIndices,
  getIpcChannelParameterIndices,
  setIpcResultParameterIndices,
  getIpcResultParameterIndices,
  setWindowDefinitionMetadata,
  getWindowDefinitionMetadata,
  setMenuDefinitionMetadata,
  setWindowUseMenuDefinitionMetadata,
  setMenuContributionDefinitionMetadata,
  getMenuDefinitionMetadata,
  getWindowUseMenuDefinitionMetadata,
  getMenuContributionDefinitionMetadata,
  setMenuFragmentDefinitionMetadata,
  getMenuFragmentDefinitionMetadata,
  setWindowRendererDefinitionMetadata,
  getWindowRendererDefinitionMetadata,
  setMenuRendererDefinitionMetadata,
  getMenuRendererDefinitionMetadata,
  addWindowCommandMetadata,
  getWindowCommandMetadata,
  addMenuCommandMetadata,
  getMenuCommandMetadata,
  addMenuItemMetadata,
  getMenuItemMetadata,
  addMenuItemHandleInMainMetadata,
  getMenuItemHandleInMainMetadata,
  addMenuItemForwardToRendererMetadata,
  getMenuItemForwardToRendererMetadata,
  addWindowEmitMetadata,
  getWindowEmitMetadata,
  getWindowEmitMetadataForMethod,
  addWindowRendererSubscriptionMetadata,
  getWindowRendererSubscriptionMetadata,
  addMenuRendererSubscriptionMetadata,
  getMenuRendererSubscriptionMetadata,
  addWindowMainSubscriptionMetadata,
  getWindowMainSubscriptionMetadata,
};
